# Generated by Django 5.0.6 on 2024-05-18 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractrule',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_system.contract'),
        ),
    ]
